# -*- coding: utf-8 -*-
"""GDP GROWTH.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SRdvC9edfymeJPsEm0Cvayal0CpqEtym
"""

import pandas as pd

# FRED CSV download link for Real Gross Domestic Product (GDP), quarterly
gdp_url = "https://fred.stlouisfed.org/graph/fredgraph.csv?id=GDP"

# Read the CSV from FRED
gdp_df = pd.read_csv(gdp_url)

# Rename columns
gdp_df.columns = ["Date", "GDP"]

# Convert Date to datetime
gdp_df["Date"] = pd.to_datetime(gdp_df["Date"])

# Drop missing values
gdp_df.dropna(inplace=True)

# Optional: Calculate GDP growth percentage
gdp_df["GDP_Growth"] = gdp_df["GDP"].pct_change() * 100

# Drop first row (NaN growth)
gdp_df.dropna(inplace=True)

# Save to CSV
gdp_df.to_csv("gdp_data.csv", index=False)

# Show last 5 rows
print(gdp_df.tail())