# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SRdvC9edfymeJPsEm0Cvayal0CpqEtym
"""

import pandas as pd
import yfinance as yf
import warnings

# Suppress yfinance warnings
warnings.filterwarnings("ignore", category=FutureWarning, module="yfinance")

# Download S&P 500 monthly data (from Jan 2000 to end of 2024)
sp500 = yf.download("^GSPC", start="2000-01-01", end="2024-12-31", interval="1mo", auto_adjust=True)

# Keep only the 'Close' column (you can also keep 'Open', 'High', etc. if you want)
sp500_df = sp500[['Close']].copy()

# Reset index (Date) and clean
sp500_df.reset_index(inplace=True)
sp500_df.dropna(inplace=True)

# Save to CSV
sp500_df.to_csv("sp500_data.csv", index=False)

# Show last 5 rows
print(sp500_df.tail())