# -*- coding: utf-8 -*-
"""unemployment.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SRdvC9edfymeJPsEm0Cvayal0CpqEtym
"""

import pandas as pd

# FRED CSV download link for Unemployment Rate (UNRATE), monthly
unemployment_url = "https://fred.stlouisfed.org/graph/fredgraph.csv?id=UNRATE"

# Read the CSV from FRED
unemp_df = pd.read_csv(unemployment_url)

# Rename columns to be clear
unemp_df.columns = ["Date", "UnemploymentRate"]

# Convert Date to datetime format
unemp_df["Date"] = pd.to_datetime(unemp_df["Date"])

# Drop missing values
unemp_df.dropna(inplace=True)

# Save to CSV
unemp_df.to_csv("unemployment_data.csv", index=False)

# Print the last 5 rows
print(unemp_df.tail())