/**
 * AI Reasoning Panel
 */
import { motion } from 'framer-motion';
import { Brain, Sparkles } from 'lucide-react';
import { Card, CardHeader, CardTitle, CardContent } from './ui/Card';
import type { FullPredictionResponse } from '../types/api';

interface ReasoningPanelProps {
  prediction: FullPredictionResponse | null;
}

export function ReasoningPanel({ prediction }: ReasoningPanelProps) {
  const reasoning = prediction?.tier3_prediction?.reasoning || prediction?.reasoning || '';

  if (!reasoning) {
    return (
      <Card>
        <CardHeader>
          <CardTitle className="title-inline">
            <Brain size={18} color="#c084fc" />
            AI Reasoning
          </CardTitle>
        </CardHeader>
        <CardContent>
          <p className="center-note">No reasoning available</p>
        </CardContent>
      </Card>
    );
  }

  return (
    <Card>
      <CardHeader>
        <CardTitle className="title-inline">
          <Brain size={18} color="#c084fc" />
          AI Reasoning
        </CardTitle>
      </CardHeader>
      <CardContent>
        <motion.div
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          transition={{ duration: 0.5 }}
          className="reasoning-block"
        >
          <div className="reasoning-bar" />
          <div className="reasoning-body">
            <p className="reasoning-text">
              {reasoning}
            </p>
          </div>
          <div className="reasoning-note">
            <Sparkles size={12} />
            <span>Generated by Hybrid MLP + LLM Model</span>
          </div>
        </motion.div>
      </CardContent>
    </Card>
  );
}



