
-- Tables for Tier 1 Data

CREATE TABLE IF NOT EXISTS macro_indicators (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date DATE NOT NULL,
    gdp_growth FLOAT,
    inflation_rate FLOAT,
    unemployment_rate FLOAT,
    interest_rate FLOAT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS geopolitics (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date DATE NOT NULL,
    event_summary TEXT,
    impact_score FLOAT, -- -1.0 to 1.0
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS sentiment (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date DATE NOT NULL,
    source VARCHAR(50), -- 'news', 'twitter', etc.
    sentiment_score FLOAT, -- -1.0 to 1.0
    headline TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Tables for Tier 2 Processed Data

CREATE TABLE IF NOT EXISTS processed_features (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date DATE NOT NULL UNIQUE,
    normalized_macro JSONB,
    sentiment_vector JSONB,
    geopolitics_vector JSONB,
    combined_vector JSONB,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Tables for Tier 3 Predictions

CREATE TABLE IF NOT EXISTS predictions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    prediction_date DATE DEFAULT CURRENT_DATE,
    sp500_direction VARCHAR(10), -- 'UP' or 'DOWN'
    confidence_score FLOAT,
    sector_recommendations JSONB,
    top_stocks JSONB,
    model_version VARCHAR(50),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);
